#Read in Packages

install.packages('devtools', force = TRUE)
devtools::install_github("rstudio/shinyapps", force = TRUE)
devtools::install_github('byzheng/leafletplugins', force = TRUE)
devtools::install_github('byzheng/leaflet', force = TRUE)
library(devtools)
library(leaflet)
library(leafletplugins)
library(shiny)
library(rgdal)
library(magrittr)
library(raster)
library(dplyr)
library(ggplot2)
